[package]
name = "double-clicker"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
macroquad = "=0.3.24"
git-version = "=0.3.5"

[profile.release]
strip = true
lto = true
